### ISSUE TITLE
Issues when using Touch ID for sudo

### ISSUE THREAD

**Issue by DeEskalator** [buresdv/Cork#131]
Hey, 
I really love Cork. However I have some issues because of the specific configuration of my system. 

I use Touch ID to legitimate every sudo-request on my system by adding 
`auth sufficient pam_tid.so` to `/etc/pam.d/sudo`

When I now install something that requires sudo-rights (for instance Adobe DNG Converter) it opens the Touch ID prompt which is out of focus so I need to click on it first before using Touch ID. Not the most comfortable thing. 

<img width="903" alt="Screenshot 2023-08-20 at 12 27 46" src="https://github.com/buresdv/Cork/assets/47759580/f7d4b10e-80b8-4cb7-a8c5-4f716edfa53b">

After that, the little white rectangle of the screen doesn't disappear, even if you click next to it or something. It only disappears when pressing esc, something that may not be figured out by every user.

Even if I disable the Touch ID legitimization for sudo on my machine (the default on every Mac), the issue with that white rectangle still exists.

Hope you can do something about this and make your great software even better

**Comment by buresdv** [comment]
Hey, thanks for the encouraging words and the report!

Concerning that triangle, that's a SwiftUI bug that is hopefully fixed in macOS 14. Check out this thread where we tested it and one of Apple's SwiftUI engineers showed up as well: https://mstdn.social/@davidbures/110910180739592409

Now, concerning the sudo thing. Cork can’t do anything about it, since it doesn't _really_ run any sudo operations. All operations that require side are actually executed by Homebrew itself; all Cork does is tell Homebrew to execute a command then then hands control of the process to Homebrew. So I can’t really do anything about it.

There are plans for executing the sudo commands within Cork, and then I would be able to control their behavior, but that requires writing privileged helpers, that don’t have a Swift way of writing them, and I don’t know Objective-C. This is also such an obscure topic that finding any useful documentation is almost impossible. So until Apple updates them, I can’t really do anything about that, either 🥲

**Comment by deinspanjer** [comment]
I didn't know about the ability to add TouchID support for sudo, so that was a great thing to read here!

I can confirm that the little box did not appear when I try to do an update and get a sudo TouchID prompt, so it does look like Apple fixed that particular issue.

Unfortunately, I do still get errors related to sudo after providing my TouchID, but that might be a completely different issue, so I'll take that feedback elsewhere. :)

**Comment by buresdv** [comment]
Please refer to #340. This discussion is all over the place and it would be great to consolidate it in one plase :)
